### PR TITLE
feat(project): collaboration tab has inside issues and merge requests

### LINKED ISSUE #446: Buttons in Kus tab have a wrong format
[I'm on dev.renku.ch]

image

Could/should it be on one line?

### LINKED ISSUE #599: Add Collaboration Tab
# Description

- The Ku and Pending Changes tabs should become subtabs of a "Collaboration tab"
- Ku should be renamed to "Issue"
- Pending Changes should be renamed to "Merge Request"

### PR DESCRIPTION
**Pull request by vfried**
I created a new tab that has inside Issues that where previously Kus and also Merge Requests that where before Previous Changes.

I decided to refactor the way the issues look:
image

Before they looked like:
image

There is one layout issue i couldn't solve, when clicking on a merge request the "merge requests" tab gets unselected:
image

I can try and fix this when i'm back or leave it and create a bug for this.

I can't deploy to virginiatest because is being used but you can use this image to test: virfried/renku-ui:0.6.5-e392a4b

Closes #599 
Closes #446

### CODE REVIEW

**Comment by lorenzo-cavazzi** [comment]
The `Issues` part is amazing! I didn't find any problem there.

I have only a request (that may be moved to a separate issue): when creating a new issue, I end up on a page that is not part of the new `Collaboration` tab. It would be great if the "New Issue" page would be moved there. The url could be changed from `/issue_new` to `/collaboration/issues/new` to be coherent with the current routing (`/collaboration/issues*`) and to simplify including it in the tab.

**Comment by lorenzo-cavazzi** [comment]
this seems to address also #446

**Comment by rokroskar** [comment]
This is looking really good! Did you leave "pending change" in a few places on purpose? e.g. 
image and image

**Comment by rokroskar** [comment]
One more minor thing - the `x` you use here is used in gitlab for failed CI jobs/pipelines: 
image

**Comment by vfried** [comment]
> This is looking really good! Did you leave "pending change" in a few places on purpose? e.g.

Just to confuse the users haha I just changed the "pending changes" i missed.

Regarding the icons, that's a good point... I'll try to replace them for something better.

**Comment by rokroskar** [comment]
Hmm I'm wondering if it would be better to have the issues display in a single pane rather than side-by-side with the issue list? Visualizing an embedded notebook becomes very cluttered: https://virginiatest.dev.renku.ch/projects/virginiafriedrich/zurich-bikes-2/collaboration/issues/9/

On a wide screen it's fine but on a small-ish laptop it's probably not very usable.

**Comment by ciyer** [comment]
This is not the end of the work on the issues or merge requests. 

The main change in this issue is to get the "Pending Changes" and "Kus" renamed and placed together in a better location. Since the code was being touched anyway, there were some other improvements made as well.

I agree that issues and merge requests should take up the majority of the screen width, but I want to do that in another GitHub issue.

**Comment by vfried** [comment]
I added an icon that hides/shows the issues list allowing the user to have a better overview of the issue: 

image

image

It would be nice to add a css transition to this but i am using display block/none and css doesn't suport transitons for the "display" property.

**Comment by rokroskar** [comment]
That looks great, thanks @vfried! Next, keyboard shortcuts for browsing through the issues :)

**Pull request merged**
