### PR TITLE
feat(client): update session start options and flow for resource pools 

### PR DESCRIPTION
**Pull request by leafty**
* Update the session start options to show which session classes match the compute requirements.
* Update the quick start flow to auto-select a suitable session class or fall back to the option screen if non is suitable.

Start options:
renku-ci-ui-2620 dev renku ch_projects_johann thiebaut1_another-playground-project_sessions_new
renku-ci-ui-2620 dev renku ch_projects_johann thiebaut1_another-playground-project_sessions_new (1)
renku-ci-ui-2620 dev renku ch_projects_johann thiebaut1_another-playground-project_sessions_new (2)

Quick start not finding a suitable session class:
renku-ci-ui-2620 dev renku ch_projects_johann thiebaut1_another-playground-project_sessions_new (4)

/deploy extra-values=crc.image.tag=sha-d9cef4d renku=crac-service-helm-chart renku-notebooks=feat-work-with-crac #persist #cypress

### CODE REVIEW

**Review by lorenzo-cavazzi — CHANGES_REQUESTED** [review]
The code looks good!

Thanks for updating this! I know it's a pain to read through functions like the hectic `triggerAutoStart`.
Hopefully, rewriting and simplifying some code (together with the changes for autosaves) will save us headaches when going through Notebooks code again.

I've found a couple of UX details to adjust:

**Project settings**
We should hide or disable the button to reset the value when no value is set. Otherwise, we get this error when clicking it.
image

**Start with options**
I would move the error message `This session class does not match the compute requirement` just after the dropdown. This has 2 advantages:
1.  The dropdown element doesn't move while selecting an invalid element (see gif)
    Peek 2023-06-29 17-24
2. The message isn't above the bigger warning when there is no valid class available
    image

**Comment by leafty** [comment]
> **Project settings**
> We should hide or disable the button to reset the value when no value is set. Otherwise, we get this error when clicking it.

Will do, but this seems to be an actual bug from `renku-core`.

> **Start with options**
> I would move the error message `This session class does not match the compute requirement` just after the dropdown.

👍

**Comment by lorenzo-cavazzi** [comment]
> > **Project settings**
> > We should hide or disable the button to reset the value when no value is set. Otherwise, we get this error when clicking it.
> 
> Will do, but this seems to be an actual bug from `renku-core`.

Fair point. Should we also open an issue in renku-python?

**Review by lorenzo-cavazzi — APPROVED** [review]
Lgtm :rocket: 
Let's merge it to the main feature branch

**Comment by leafty** [comment]
> Fair point. Should we also open an issue in renku-python?

https://github.com/SwissDataScienceCenter/renku-python/issues/3544

**Pull request merged**
