### PR TITLE
fix(client): correct handling of notebook search parameter with autostart

### LINKED ISSUE #2217: Link to open a session not fully working when notebook to open is specified
When composing a link to open a session on renkulab when not logged-in, we get the following  behavior:

image

The link is so composed:

[https://renkulab.io/projects/astronomy/mmoda/mmoda-request/sessions/new?autostart=1&branch=mmoda_request_c570580ab66720b3_76adbfd3aecd840a&commit=8507b7803d4b67d7d77c305e5568c00cc11307ec&notebook=api_code_c570580ab66720b3.ipynb&env%5BODA_TOKEN%5D=secret](https://renkulab.io/projects/astronomy/mmoda/mmoda-request/sessions/new?autostart=1&branch=mmoda_request_c570580ab66720b3_76adbfd3aecd840a&commit=8507b7803d4b67d7d77c305e5568c00cc11307ec&notebook=api_code_c570580ab66720b3.ipynb&env%5BODA_TOKEN%5D=secret)

We noticed that by removing the notebook we want to have opened, the link then works as expected, e.g.:

[https://renkulab.io/projects/astronomy/mmoda/mmoda-request/sessions/new?autostart=1&branch=mmoda_request_c570580ab66720b3_76adbfd3aecd840a&commit=8507b7803d4b67d7d77c305e5568c00cc11307ec&env%5BODA_TOKEN%5D=secret](https://renkulab.io/projects/astronomy/mmoda/mmoda-request/sessions/new?autostart=1&branch=mmoda_request_c570580ab66720b3_76adbfd3aecd840a&commit=8507b7803d4b67d7d77c305e5568c00cc11307ec&env%5BODA_TOKEN%5D=secret)

and interestingly, the notebook I was previously attempting to open, is now opened

image

Please ask any detail I might have missed

Thanks

### PR DESCRIPTION
**Pull request by leafty**
Details:
* Anonymous sessions URLs have a token  parameter (e.g. `https://dev.renku.ch/sessions/anon-2d034-playground-2dproject-6a61ddaf?token=anon-some-uuid`).
* Combined with `notebook=foobar.ipynb`, the UI tries to open `https://dev.renku.ch/sessions/anon-2d034-playground-2dproject-6a61ddaf?token=anon-some-uuid/lab/tree/foobar.ipynb` and this fails. The `/lab...` part should be added before `?token=`.

Fixes #2217.

/deploy #persist #cypress

### CODE REVIEW

**Review by lorenzo-cavazzi — CHANGES_REQUESTED** [review]
The code looks good, but it actually introduces a regression in some cases.

Try to start a notebook **as non-logged user** from the File Viewer (the screenshot shows you the icon)
https://renku-ci-ui-2469.dev.renku.ch/projects/johann.thiebaut/flights-tutorial-2022-04-19/files/blob/notebooks/FilterFlights.ipynb

image

With this change, it triggers an "undefined path" error (on the left in the next screenshot)  while it was working before (on the right)

image

-----

More in general, I know the Notebooks code is messy, and we will adjust that soon.
In the meanwhile, it would make sense to move this function in the `NotebooksHelper` object in the "Notebooks.state.js" file, and perhaps add a test with a few common URLs in the "Notebooks.test.js" file.

**Comment by leafty** [comment]
> Try to start a notebook **as non-logged user** from the File Viewer (the screenshot shows you the icon) https://renku-ci-ui-2469.dev.renku.ch/projects/johann.thiebaut/flights-tutorial-2022-04-19/files/blob/notebooks/FilterFlights.ipynb
>
> With this change, it triggers an "undefined path" error (on the left in the next screenshot) while it was working before (on the right)

This bug already exists in `master`, you can see e.g. https://renkulab.io/projects/johann-michael.thiebaut/flights-tutorial/files/blob/notebooks/FilterFlights.ipynb in a private window. The session start link is not correct.

I will create an issue and a bug fix for this.

**Comment by lorenzo-cavazzi** [comment]
Ha sorry, I tested the wrong way. Yes, it's broken already in master; it would be nice to fix that in the same PR, but feel free to create a separate issue+PR if you prefer.

Could we address the last part of this comment before merging? https://github.com/SwissDataScienceCenter/renku-ui/pull/2469#pullrequestreview-1387726406

**Comment by leafty** [comment]
> Ha sorry, I tested the wrong way. Yes, it's broken already in master; it would be nice to fix that in the same PR, but feel free to create a separate issue+PR if you prefer.
> 
> Could we address the last part of this comment before merging? [#2469 (review)](https://github.com/SwissDataScienceCenter/renku-ui/pull/2469#pullrequestreview-1387726406)

Yes, I am thinking of moving this to a utils file in TypeScript and create a few test cases.

**Comment by lorenzo-cavazzi** [comment]
> > Ha sorry, I tested the wrong way. Yes, it's broken already in master; it would be nice to fix that in the same PR, but feel free to create a separate issue+PR if you prefer.
> > Could we address the last part of this comment before merging? [#2469 (review)](https://github.com/SwissDataScienceCenter/renku-ui/pull/2469#pullrequestreview-1387726406)
> 
> Yes, I am thinking of moving this to a utils file in TypeScript and create a few test cases.

That sounds great!

**Review by lorenzo-cavazzi — APPROVED** [review]
It works well now!
I spent some time checking the slow rendering component's problem but couldn't identify the underlying issue.

Btw this also includes #2479 , right?

**Comment by leafty** [comment]
> It works well now! I spent some time checking the slow rendering component's problem but couldn't identify the underlying issue.
> 
> ~Btw this also includes #2479 , right?~ Nvm I see there are just some commits in common. Let's merge this to master and then I'll give a look at #2479

I merged #2479 into this branch to check if the feature works end to end with both fixes.

I would also merge #2479 first, I still want to add a couple of tests here.

**Review by lorenzo-cavazzi — APPROVED** [review]

**Pull request merged**
