### PR TITLE
feat(dataset): add dataset to project active and with migration check

### LINKED ISSUE #964: Uncomment the "Add to project" button
We commented the add to project button (inside datasets) and we should uncomment this when things are ready.

### PR DESCRIPTION
**Pull request by vfried**
When importing a dataset if the project you want to import the dataset to needs to be migrated you will see a warning message...

image

Testing available: https://virginiatest.dev.renku.ch/

In order to test this, you should try to import a dataset into a project that needs to be migrated using the add to project button. 

Closes #964

### CODE REVIEW

**Comment by rokroskar** [comment]
@lorenzo-cavazzi the import will work in that case though it will not show up in the UI... maybe it's ok for now until we switch to checking project-local dataset data with the core service instead of the KG?

**Comment by lorenzo-cavazzi** [comment]
@rokroskar for me it's ok but this may be confusing for the users. If I try to re-import the dataset again after the KG integration is activated (something I assume one would try) I would get this error

Screenshot_20200810_163111

The information I get from the UI are conflicting.
I believe checking the webhook once the target project is selected is pretty easy, just a matter of invoking `GET /projects/<id>/graph/webhooks/validation` for the target project.

**Comment by rokroskar** [comment]
Sure, I'm not saying the current situation is not confusing - but I'm wondering if it makes sense working around it too much since a much better fix will be available soon.

**Comment by lorenzo-cavazzi** [comment]
Yeah I see your point.
I would rather put the feature on hold since the same thing can already be achieved by importing the dataset from the target project instead of "pushing" it from the source project (and that's error-free), but if you prefer to go on we can move forward with this PR.

**Pull request merged**
