### PR TITLE
feat(datasets): with link to external source and author affiliation

### LINKED ISSUE #687: Adapt dataset ui to new changes
Show link to external dataset.
Add next to the author the affiliation of it.

Changes in the KG: https://github.com/SwissDataScienceCenter/renku-graph/pull/188

### PR DESCRIPTION
**Pull request by vfried**
Added link to external source and author affiliation.

image
Test Env: https://virginiatest.dev.renku.ch/

Closes #687

### CODE REVIEW

**Comment by rokroskar** [comment]
This is looking really nice! I would maybe add the link provided by the `sameAs` field, if it exists, and display it with the details of the dataset since that is a critical piece of identifying information.

**Comment by vfried** [comment]
> This is looking really nice! I would maybe add the link provided by the `sameAs` field, if it exists, and display it with the details of the dataset since that is a critical piece of identifying information.

Like this.. ?
image

**Comment by rokroskar** [comment]
I wonder if it would make sense to have both, e.g. 

> source: https://zenodo.org/...
> DOI: https://doi.org/...

If the doi doesn't exist we just show the source.

**Comment by vfried** [comment]
Done...
image

**Comment by rokroskar** [comment]
That makes sense to me! and if DOI is not there that line is missing?

**Comment by vfried** [comment]
> That makes sense to me! and if DOI is not there that line is missing?

Yes

**Pull request merged**
