### PR TITLE
feat: added download button to top bar and file size

### LINKED ISSUE #974: display file size in renkulab file browser
## Motivation

When users are starting an interactive environment they have to decide whether to include all LFS files or none using the check box. But unless they go to gitlab (or already know how much data is in the project because they recently added the data and it's their own project), they don't know how much data will be pulled into the session.

## Proposal

include the total LFS file size vs the project file size, and the file sizes on the file browser for each file.

## Context

This could also make it easier for us to point out when someone accidentally added large data to their project.

### PR DESCRIPTION
**Pull request by vfried**
Download button added to the nav bar of the file...

image

I also did some cosmetic changes and added the file size
This is how it looked before...
image

Closes #1133 
Closes #974 
Addresses the first part of #1083

### CODE REVIEW

**Review by ciyer — APPROVED** [review]
Looks great, works great, even for LFS files! The file size indication is very helpful. Glad it was so easy to do. Tested on public and private projects, works everywhere I tried.

**Comment by vfried** [comment]
Thanks for reviewing, I don't absolutely love the download icon but I thought it was the best choice. There is also a file download button in font awesome but it doesn't look as good.

Currently waiting for approval of the product owner and then I will merge this.

**Comment by vfried** [comment]
@ciyer thanks for fixing the linting, it should be fixed now on my vscode

**Comment by rokroskar** [comment]
This is going to be loved by many :) 

One small comment: is it possible to make the file nav bar look the same for the lineage view and the file view? I don't see a reason why I shouldn't have the option to download the file (or see its size) if I'm looking at its lineage...

**Comment by vfried** [comment]
> I don't see a reason why I shouldn't have the option to download the file (or see its size) if I'm looking at its lineage...
I thought maybe the users might think that they could download the lineage... the file size could be less confusisng i guess

**Comment by vfried** [comment]
Regarding the file size.. for git lfs files we will have to fetch the file and read it before we can display the size, since we don't get it from gitlab... not sure if we want to do that or not.

**Comment by vfried** [comment]
Regarding file size inside lineage we can:
1- display file size for files that are not lfs
2- display file sizes for all files, this imples fetching files that are lfs to read the file size
3- leave it as it is

Regarding the download button, shall i add it? ---> i need a confirmed desition

**Comment by vfried** [comment]
With file size and download button for graph as well...

**Review by rokroskar — APPROVED** [review]
Looks great now, thanks!

**Review by ciyer — APPROVED** [review]
🎉

**Pull request merged**
