### PR TITLE
Remove outdated @nteract packages from package.json

### PR DESCRIPTION
**Pull request by ciyer**
We use some "@neteract" packages that are no longer maintained. These should be replaced with ones that are current.

/deploy #persist

### CODE REVIEW

**Comment by ciyer** [comment]
Makes progress on #2117, but there are still some packages to remove.

**Comment by ciyer** [comment]
To test, look at some notebooks in Renku and make sure that the notebooks render as before; check that the "override code visibility" feature still works. (N.B. The syntax-highlighting colors are slightly different because a different library is used.)

For example

| New | Old |
|------|-----|
| https://renku-ci-ui-2136.dev.renku.ch/projects/cramakri/swiss-energy/files/blob/notebooks/viz/Questions.run.ipynb | https://dev.renku.ch/projects/cramakri/swiss-energy/files/blob/notebooks/viz/Questions.run.ipynb |
| https://renku-ci-ui-2136.dev.renku.ch/projects/cramakri/mathjax/files/blob/notebooks/latex-notebook.ipynb | https://dev.renku.ch/projects/cramakri/mathjax/files/blob/notebooks/latex-notebook.ipynb |

**Review by lorenzo-cavazzi — COMMENTED** [review]
The changes work great! Thanks for looking into this tedious issue!

I see a couple of errors on e2e. I'm surprised to see them (hopefully #2142 will improve the stability of e2e :crossed_fingers: ), but I also get an error on the `project` when running them locally. Could you give it a look?

Otherwise, ready to merge!

**Review by andre-code — DISMISSED** [review]
I really like the new styles for the notebooks ✨ I find it much more readable, and also the code looks good to me.

**Review by lorenzo-cavazzi — APPROVED** [review]

**Pull request merged**
