### PR TITLE
chore(ci): Update renku actions to v0.5.0

### PR DESCRIPTION
**Pull request by olevski**
Automated changes by [create-pull-request](https://github.com/peter-evans/create-pull-request) GitHub action

/deploy #persist

### CODE REVIEW

**Comment by olevski** [comment]
The setup is as follows:
- if you do not provide `#persist` in the PR description when you specify `/deploy` then the CI deployment is deleted after the acceptance tests complete
- if you provide `#persist` the deployment is kept until the PR is closed.
- when the PR is closed the namespace of the deployment is also deleted
- when the acceptance tests complete AND `#persist` is not used the CI deployment is deleted but the namespace is not deleted in k8s - this makes it possible to reuse the TLS secret and not hit the limits for requesting certs with letsencrypt when the acceptance tests for the same PR are run many times

**Comment by olevski** [comment]
This is failing because the PR that changes these actions in the main renku repo needs to be merged. First. Will keep this as a draft until that is taken care of.

**Comment by olevski** [comment]
I was "lucky" enough to have the acceptance tests fail after making the latest updates. See here for how things look when a test fails.
https://github.com/SwissDataScienceCenter/renku-ui/actions/runs/1711637342

**Comment by olevski** [comment]
I will rerun the tests so that they pass and this can be merged. Either way this is ready for review.

**Comment by ciyer** [comment]
Superseded by #1677

**Comment by olevski** [comment]
Lorenzo correctly noted that this PR has manual changes that need to be merged and would be lost if 0.5.0 is merged only

**Comment by olevski** [comment]
I will update this to instead supersede the other PR and close the other PR (https://github.com/SwissDataScienceCenter/renku-ui/pull/1677)

**Review by ciyer — APPROVED** [review]
👍 Thanks for putting this together for us!

**Pull request merged**
