### PR TITLE
Use graph services for lineage display

### PR DESCRIPTION
**Pull request by ableuler**
- Remove dot-file parsing from lineage component
- Query graph api instead of artefact api
- Adapt to new graph serialization

Addresses #362 
Merge after #374

### CODE REVIEW

**Comment by ableuler** [comment]
The PR is almost finished, some sanity checks and comparisons with the previous graph need to be done.

**Comment by lorenzo-cavazzi** [comment]
This is the comparison between the old and the new lineage output for a sample file taken from the Renku tutorial. The new version is on the right.

Lineage comparison

**Comment by lorenzo-cavazzi** [comment]
requires #369 to enable the webhooks in gitlab for lineage generation

**Comment by lorenzo-cavazzi** [comment]
Preview temporary available at https://graphpreview.dev.renku.ch/

**Comment by rokroskar** [comment]
This seems to work as advertised - @ableuler @jirikuncar the only thing it's missing is some more data from the sparql query

**Comment by ciyer** [comment]
Code looks good! I'm surprised it's so few changes. The only thing I do not like (and I do not know if you can control this) is the content of the graph. This new graph is unreadable. As Rok requested, we need to get the others involved and make sure the same graph data is made available from the backend.

**Comment by lorenzo-cavazzi** [comment]
New preview available at https://graphpreview.dev.renku.ch/

Now the content looks better (image 1) but we still have some extra nodes (image 2, `renku update` on top). I changed the commit nodes to show the renku command. If it looks good enough I would merge the PR and let content-related problems to be solved in the gateway

**Comment by rokroskar** [comment]
I don't see any extra nodes here: https://graphpreview.dev.renku.ch/projects/72/files/lineage/figs/grid_plot.png

**Comment by rokroskar** [comment]
OK I see now -- I think that's because the lineage query is not returning all the parents -- can you confirm @ableuler ?

**Comment by ableuler** [comment]
> OK I see now -- I think that's because the lineage query is not returning all the parents -- can you confirm @ableuler ?

I'm not sure I understand what you mean. For me the main question is if the "forward lineage" query should also be able to change direction and go backwards. I would say yes, but only one step. So the zhbikes_parquet nodes should be there, but not the renku update notes above them. I'm not at all sure if and how this can be achieved in the SPARQL query itself. But I think doing some filtering in python after the query is also fine.

**Comment by lorenzo-cavazzi** [comment]
This would be the updated version with a single step backward

Screenshot from 2019-04-04 11-06-37

**Comment by lorenzo-cavazzi** [comment]
Let me know if you think it's better and I'll merge the fix on `gateway`.

Btw I am going to merge this PR

**Comment by rokroskar** [comment]
> Let me know if you think it's better and I'll merge the fix on gateway.

you mean the fix is deployed?

**Comment by lorenzo-cavazzi** [comment]
Not yet, I am creating a PR for that on `renku-gateway`. Could you approve this PR in the meanwhile?

**Comment by lorenzo-cavazzi** [comment]
Updated on https://graphpreview.dev.renku.ch/

**Comment by rokroskar** [comment]
Looks great! Thanks @lorenzo-cavazzi @ableuler and @jirikuncar! 🎉

**Pull request merged**
