### PR TITLE
fix(client): handle errors from the getSessions query in the Dashboard

### LINKED ISSUE #2873: Handle errors from the servers endpoint in the Dashboard
## Description

The dashboard, and specifically the projects section, keeps refreshing at short intervals when the `GET /servers` endpoint from renku-notebooks fails to respond.
We should handle the error better and prevent this behavior. Best would be to show an error message so that users know sessions aren't currently shown.

## Reproduce

Use the e2e tests, pick one for rendering the dashboard and remove the servers endpoint response (or fail it)

https://github.com/SwissDataScienceCenter/renku-ui/assets/43481553/008500fd-6eba-4734-842b-723c6702cd36

### PR DESCRIPTION
**Pull request by leafty**
Fixes #2873.

Introduces a new context and component to handle RTK Query errors in the case when nested components use an errored query.

/deploy

### CODE REVIEW

**Review by lorenzo-cavazzi — COMMENTED** [review]
Nice solution and the code looks good :+1: 

Should we show a banner on the Dashboard mentioning there is a problem with sessions when we get errors? Otherwise, users do not know that's the case and all looks fine
image

**Comment by leafty** [comment]
> Should we show a banner on the Dashboard mentioning there is a problem with sessions when we get errors? Otherwise, users do not know that's the case and all looks fine

I add 3befaf0, but I am not sure if users will understand the error message.

**Comment by lorenzo-cavazzi** [comment]
Oh, I meant something more generic, like a Warning saying "Sessions are currently unavailable"

**Comment by leafty** [comment]
> Oh, I meant something more generic, like a Warning saying "Sessions are currently unavailable"

Done in 65d40d3.

**Review by lorenzo-cavazzi — CHANGES_REQUESTED** [review]
Very nice solution!

I noticed the function `extractRkErrorMessage` isn't working as expected. I'm unsure whether the Notebooks error is different from the Core error, or if something else is wrong in the logic there.
It would be great if you had some spare time to look at it. Otherwise, feel free to remove the specific error message and we can make a follow-up issue to fix the "RkErrorMessage" component(s) -- it would be great to have one that "just works", or to clearly distinguish between "renku-core" and "renku-notebooks" errors.

image

**Comment by leafty** [comment]
> Very nice solution!
> 
> I noticed the function `extractRkErrorMessage` isn't working as expected. I'm unsure whether the Notebooks error is different from the Core error, or if something else is wrong in the logic there. It would be great if you had some spare time to look at it. Otherwise, feel free to remove the specific error message and we can make a follow-up issue to fix the "RkErrorMessage" component(s) -- it would be great to have one that "just works", or to clearly distinguish between "renku-core" and "renku-notebooks" errors.

I think it's not as simple because if I remove the notebooks service I get a proper error:
image

**Review by lorenzo-cavazzi — APPROVED** [review]

**Pull request merged**
