### PR TITLE
feat: make apearance of switch state clearer

### LINKED ISSUE #1357: UI Design Update -- Fix switch state
## Description

The state of these switches is counter-intuitive.

image

"Lineage" is selected, but to my eye, it looks like "Contents" is selected.

### PR DESCRIPTION
**Pull request by ciyer**
Fix #1357

## Look

**Contents Selected**

image

**Hover over Lineage**

image

**Add Dataset**

image

**Style Guide**

image

**Notebook Launch**

image

/deploy

### CODE REVIEW

**Review by vfried — COMMENTED** [review]
Things look good, I'm not 100% sure the colors are clear for the user since we have similar buttons but the white means "unselected"

image

When i tried to use the new switch my first intention was to click on the white button, nothing was changing and i thought the button was "broken" since the button you should click looks like a deactivated button to me.

image

We can merge this and if it's confusing we can change it again I guess.

**Comment by ciyer** [comment]
I made the suggested changes and applied the styling to the new dataset form as well.

**Comment by vfried** [comment]
image

Well done, I like the way this looks and it's clear as well.

I don't like these buttons here... but it's more about the combination of colors, maybe this is something that Luca can redesign for us. We could also remove the switch from that file or put it somewhere else.

image

Shall we change this here as well....
image

image

**Comment by vfried** [comment]
Thanks for addressing the changes I requested. Things are looking really good. 

I just have two small thing to point out... 

1. I see there is a weird white border when an element is selected, could we get rid of it?
image

2. there is an issue with a switch in the new sessions:
- no clicks:
image

- click on: 0.5
image

- click on 0.1
image

- click on 0.5 
image

I imagine this is not expected behaviour, could we fix it?

**Comment by ciyer** [comment]
> 2. there is an issue with a switch in the new sessions

Yes, I created an issue for this: #1424

I tried to make a quick fix, but I need a bit more time to understand the problem, and the code is unrelated to the switch state code, so I think it is better to handle this in a separate PR.

**Comment by vfried** [comment]
All looks good buuuuut... there is one last issue i found here: when things are collapsed the bar is bigger (height) than when they are not.

**Review by vfried — APPROVED** [review]
Things look good now, thanks for addressing the changes!

**Pull request merged**
