### PR TITLE
feat(client): add import dataset to new project (#1604)

### LINKED ISSUE #1604: Create a new project based on a dataset
## Motivation

It is possible to _add_ a dataset to a project, it would be nice to add an option to **create** a new project and add the dataset.

## Proposal

The add button, which currently opens a popup, should change. It should open a **new page** that lets the user either pick an existing project or create a new project, using the new project form.

image

If a new project is created, that should be the first step, the second step is to add the dataset to the project.

- We may want to show some more information about the dataset than just the title in this new form.

### LINKED ISSUE #1638: Prevent importing datasets with differetn versions
## Motivation

Now that we support multiple renku-core versions, users may try to add datasets from a project with an incompatible renku metadata version.
That should be prevented (verify if we currently have this information. If not, we may delay this to just before finalizing the import: at that point, fetch the dataset's project metadata version and verify the compatibility before actually starting the import).

## Mock-ups / Design

TODO

## Progress

- [ ] API Design (sprint-??)
- [ ] UI Implementation

### LINKED ISSUE #1666: White death after clicking the back button from new project form
## Description

Uncontrolled error when pressing the back button from the new project form causing a white screen in the application. The error in the console indicates that the map function is not valid for `meta.namespace.visibilities`, this is because the data type changes from Array to object when the event the return back is triggered.

## Reproduce

1. Go to https://renkulab.io/projects
2. Click on the New Project button
3. Click on the return back browser button
4. See white screen

bug-after-new-project-form

<details><summary>Browser Output</summary>
<pre>
instrument.ts:129 TypeError: n.namespace.visibilities.map is not a function
    at a.value (ProjectNew.present.js:642:51)
    at Fa (react-dom.production.min.js:182:192)
    at za (react-dom.production.min.js:181:224)
    at gs (react-dom.production.min.js:263:490)
    at cl (react-dom.production.min.js:246:265)
    at sl (react-dom.production.min.js:246:194)
    at Js (react-dom.production.min.js:239:172)
    at react-dom.production.min.js:123:115
    at t.unstable_runWithPriority (scheduler.production.min.js:19:467)
    at Ui (react-dom.production.min.js:122:325)
    at Yi (react-dom.production.min.js:123:61)
    at Gi (react-dom.production.min.js:122:496)
    at Ks (react-dom.production.min.js:230:156)
    at ma (react-dom.production.min.js:163:512)
    at e.p (connectAdvanced.js:88:7)
    at e.t.handleChangeWrapper (Subscription.js:95:12)
    at Object.b [as dispatch] (redux.js:296:32)
    at e (<anonymous>:2557:20)
    at Object.dispatch (index.js:11:16)
    at Object.dispatch (<anonymous>:3631:80)
    at e.value (Model.js:157:21)
    at e.value (Model.js:245:22)
    at e.value (Model.js:231:10)
    at e.value (Model.js:287:20)
    at e.<anonymous> (ProjectNew.state.js:495:16)
    at c (runtime.js:63:40)
    at Generator._invoke (runtime.js:294:22)
    at Generator.next (runtime.js:119:21)
    at r (asyncToGenerator.js:3:20)
    at s (asyncToGenerator.js:25:9)
    at asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at e.<anonymous> (asyncToGenerator.js:21:12)
    at e.<anonymous> (main.0de3a2aeb3851eeb19ac-b26aa16.chunk.js:2:410530)
    at a.<anonymous> (ProjectNew.container.js:499:22)
    at c (runtime.js:63:40)
    at Generator._invoke (runtime.js:294:22)
    at Generator.next (runtime.js:119:21)
    at r (asyncToGenerator.js:3:20)
    at s (asyncToGenerator.js:25:9)
</pre>
</details>

### PR DESCRIPTION
**Pull request by andre-code**
### Description
PR to include form for Add a dataset to new project

### Successful import case:
Add dataset to new project OK

### Unsuccessful import case:
Add dataset to new project

E2e test will be included in other PR

fix #1604
fix #1638
fix #1666
/deploy #persist renku=000-acceptance-tests

### CODE REVIEW

**Review by lorenzo-cavazzi — CHANGES_REQUESTED** [review]
Great PR! I have a few minor points (see inline) and a doubt on `React.createContext` that we can discuss offline. After clarifying that I'll finish the review.

**Comment by andre-code** [comment]
Validations Added

|    | Dataset Project | Target Project (existing or new) |
| ------------- | ------------- | ------------- |
| Dataset Exists | x | - |
| Cache migration | x | x |
| Is supported (project version supported, docker renku status...) | x | x |
| Version compatibility (dataset project version >= target project version) | x | x |

**Comment by andre-code** [comment]
@ciyer and @lorenzo-cavazzi thanks for your review and suggestions.
I have updated the PR including all of Lorenzo's suggestions and the commented solution regarding the app context.
This PR is ready for your review 👌.

**Review by ciyer — APPROVED** [review]
This is a feature that has been requested for a while, and I think this is a very nice implementation! 🎉 

In testing, we identified the problem that the KG does not correctly index projects created this way, but it looks like they are creating a fix, so there is no need to delay the merge in the UI.

**Pull request merged**
