### PR TITLE
build(client): change security context user

### PR DESCRIPTION
**Pull request by lorenzo-cavazzi**
Change security context user -- should allow telepresence v1 to run properly again

/deploy renku=000-ui-server-chart #persist

### CODE REVIEW

**Review by andre-code — APPROVED** [review]
It worked for me! 🙌👏

**Comment by lorenzo-cavazzi** [comment]
Telepresence works, but there are problems with getting the JSON values (i.e. nginx reading files). This requires more fine-tuning :unamused:

**Review by ciyer — CHANGES_REQUESTED** [review]
I think this can be closed since #1987 allows us to switch to telepresence 2 for the UI client.

**Comment by lorenzo-cavazzi** [comment]
Yes, this can be closed

**Pull request closed without merging**
