### PR TITLE
fix(client): show and use timezone aware dates

### PR DESCRIPTION
**Pull request by lorenzo-cavazzi**
We use ISO timezones strings where we should not, resulting in confusing outputs.
Here is an example where we convert to an ISO string, strip the timezone, and show the output. GitLab shows the proper time (timezone aware) while RenkuLab shows the UTC time.

image

This PR fixes it where necessary.
/deploy #persist #cypress

### CODE REVIEW

**Review by ciyer — COMMENTED** [review]
This looks ok to me, and is certainly an improvement. I noticed, though, that GitLab includes the time zone, which makes it less ambiguous. Do we want to consider including that too, or was that idea already rejected?

**Comment by lorenzo-cavazzi** [comment]
@ciyer That's a good idea! This is mostly a bugfix since the dates shown were wrong.
Can I create a follow-up issue to also show the timezone?

**Comment by ciyer** [comment]
> @ciyer That's a good idea! This is mostly a bugfix since the dates shown were wrong. Can I create a follow-up issue to also show the timezone?

I will approve then.

**Review by ciyer — APPROVED** [review]
👍

**Pull request merged**
