### PR TITLE
Shape Up #1 - Fifth prototype part1: workflow visualizer

### PR DESCRIPTION
**Pull request by lorenzo-cavazzi**
Prototype 5 - workflow details visualizer

_Work in progress -- more info coming soon_

/deploy renku-core=workflow-ui-feature-branch #persist

### CODE REVIEW

**Comment by lorenzo-cavazzi** [comment]
These are the new features for this prototype:
- Add a workflows visualizer --> [reference mockups](https://www.figma.com/file/g59LePQ8xo56RaMxIIlDqd/Workflow-Visualize?node-id=0%3A1)
- Autoscroll to top for projects with many workflows
- add `renku run` command
- change interaction on the browser elements: always open on click, collaps only on arrow click

There are a few pet projects for testing workflows in the group `Workflows pet projects` https://renku-ci-ui-2087.dev.renku.ch/projects/all?searchIn=groups&query=workflows (the link works only for logged in users)

**Comment by lorenzo-cavazzi** [comment]
P.S: these 2 changes will be addressed later

- add an info popover when a file is missing (explaining why)
- pre-select the first input/output/param/mapping when opening a new workflow

**Comment by lorenzo-cavazzi** [comment]
Thanks for the review. I fixed the issue of showing the long workflow ID on mapping targets -- it was related to a bug on the backend fixed later. Now it shows a different object.
image

In the end, I also moved the Detail tab below the mappings as it already is for inputs/outpus on simple workflows. It looks better an more coherent
image

I also totally agree on the links. I removed them from the small clickable box and added info on the details panel when the file is missing
image

**Review by ciyer — APPROVED** [review]
This is good progress here!

**Pull request merged**
