### PR TITLE
Improvements to file scrolling

### LINKED ISSUE #2336: Fix file browser scrolling
## Problem

Scrolling the file browser leads to poor UX and is partially broken. It is particularly bad in the following situations:

* Minimal content in the preview and a long list of files on the browser: in this case scrolling the browser is slow and clunky unless the mouse is hovering the broswer ([example 1](https://dev.renku.ch/projects/lorenzo.cavazzi.tech/many_files/files/blob/data/file10.txt)).
* Very long content in the preview and short list of files on the browser: in this case the file browser disappears as soon as we start scrolling ([example 2](https://dev.renku.ch/projects/lorenzo.cavazzi.tech/essm_egu_2020/files/blob/notebooks/Priestley-Taylor_equation.ipynb))

## Solution

For the file browser section, we should use the same "sticky" approach we already have in the search page. Try to scroll down there https://dev.renku.ch/search

### PR DESCRIPTION
**Pull request by ciyer**
Make either file tree or file content sticky as needed

image

image

Fix #2336 

/deploy #persist #cypress #notest renku=renku-ui-3.4.0-tests

### CODE REVIEW

**Comment by ciyer** [comment]
# Testing

Look at projects with many files or ones containing files with long content.

E.g.,

* https://renku-ci-ui-2406.dev.renku.ch/projects/lorenzo.cavazzi.tech/many_files/files/blob/.renkulfsignore
* https://renku-ci-ui-2406.dev.renku.ch/projects/lorenzo.cavazzi.tech/essm_egu_2020/files/blob/notebooks/Priestley-Taylor_equation.ipynb

These should scroll smoothly and show both file tree and content as you scroll. Also check on different browser widths.

**Review by lorenzo-cavazzi — APPROVED** [review]
This works much better than the previous solution!

**Comment by lorenzo-cavazzi** [comment]
There might be something to fix in the local e2e tests since it fails on a file-related case.

**Comment by ciyer** [comment]
Closing in favor of #2412

**Pull request closed without merging**
