### PR TITLE
refactor(client): update DateTime and Duration utilities to use luxon

### PR DESCRIPTION
**Pull request by leafty**
Fixes https://github.com/SwissDataScienceCenter/renku-ui/issues/2483.

New datetime and duration utility functions are introduced, using `luxon`.

Some datetime rendering now include the timezone, see below.

Before:
Screenshot 2023-06-15 at 14 04 39

After:
Screenshot 2023-06-15 at 14 03 39

/deploy #persist #cypress

### CODE REVIEW

**Comment by lorenzo-cavazzi** [comment]
Is this intended to replace #2508 ?

**Comment by leafty** [comment]
> Is this intended to replace #2508 ?

Yes, I am keeping it around to pick some code pieces.

**Comment by lorenzo-cavazzi** [comment]
Just a generic comment while I review: there are a few downgrades in `client/package.json`.
I assume they are not intended and are just a side effect of a merge

**Comment by leafty** [comment]
> Just a generic comment while I review: there are a few downgrades in `client/package.json`. I assume they are not intended and are just a side effect of a merge

Ah yes, thanks for noticing. I think this is because the branch was started a while back. I will fix the `package.json` file.

**Review by lorenzo-cavazzi — COMMENTED** [review]
The code looks great and the solution is really good! We can merge this after adjusting the package file :rocket: 

I wonder if it makes sense to change how we visualize dates in some places to keep consistency across the application (if you agree with the changes, this can be done either within this PR or in a separate one).

The following could be turned into relative distances with a tooltip for the specific time:
- File header indicating last commit author and time (from "Lorenzo Cavazzi 2023-06-14 15:32:40 GMT+2" to "Lorenzo Cavazzi, 2 hours ago")
  image
- Project's commits list in the "Overvieew --> Commits" tab, adding the tooltip
  image
- Workflow detail pages, both the "Creation date" and the "Last execution" fields (tbh I don't have a strong preference for this case, but consistency might be enough to justify changing them too)
  image

**Review by lorenzo-cavazzi — DISMISSED** [review]

**Review by lorenzo-cavazzi — APPROVED** [review]
Lgtm! :rocket: 
Thank you for taking care of this! :pray:  I neglected glitches on dates for too long

**Pull request merged**
