### PR TITLE
Moving Jupyter interactions to Notebook Servers

### PR DESCRIPTION
**Pull request by lorenzo-cavazzi**
This addresses the first 2 points of #340

### CODE REVIEW

**Comment by lorenzo-cavazzi** [comment]
I realized I am not verifying the user access level, showing the "start" button to everybody. I'll fix it

**Comment by lorenzo-cavazzi** [comment]
Ok now it's ready for the review

**Comment by ciyer** [comment]
I think we should remove the + > Launch Jupyter button as well. I think this is too specific a feature to need to have access to there. Let me know if you disagree.

**Comment by lorenzo-cavazzi** [comment]
I definitely agree.

Should we rename "Notebook Servers" tab? I think the definition is technically correct but I was wondering if something like "Jupyter Notebooks" or just "Notebooks" would be more user friendly.

**Comment by ciyer** [comment]
> I definitely agree.
> 
> Should we rename "Notebook Servers" tab? I think the definition is technically correct but I was wondering if something like "Jupyter Notebooks" or just "Notebooks" would be more user friendly.

I think we should eventually rename it to "interactive environments" or similar, but that can wait until we have support for easily defining environments (e.g., R Studio in addition to jupyter lab).

**Pull request merged**
