### PR TITLE
feat: add styles for project and dataset cards (#1964)

### PR DESCRIPTION
**Pull request by andre-code**
This PR add the styles for project and dataset cards and the button to start a session from the project card.

card-styles

Ref #1964 

#### Pending
- [ ] Fix acceptance tests

/deploy renku=1978-styles-cards-projects-and-datasets #persist

### CODE REVIEW

**Comment by andre-code** [comment]
Note: we agreed with Ordes not to merge it into master but into a feature branch while making the internal card for projects and datasets.

**Review by ciyer — CHANGES_REQUESTED** [review]
This looks good!

For the most part, I think the code is good, I think it could benefit from introducing a few more components in `client/src/utils/components/List.js`. I made a commit that starts this, but I think it could go a bit further.

The other thing that would be nice is to use SVG for the background images. I think the PNG files look grainy.

**Comment by andre-code** [comment]
> This looks good!
> 
> For the most part, I think the code is good, I think it could benefit from introducing a few more components in `client/src/utils/components/List.js`. I made a commit that starts this, but I think it could go a bit further.


Thanks for the feedback, I have also added new components in the List.js. Note that in kg-search that component is refactored, so in this PR I only focus on the styles and don't make this PR so extensive.


> 
> The other thing that would be nice is to use SVG for the background images. I think the PNG files look grainy.

That grainy effect is intentional in the design, those resources in Figma and zeroheight are only available in png, and I think it makes sense because they are 2 images combined.

**Review by ciyer — APPROVED** [review]
👍

**Pull request merged**
