### PR TITLE
Fix url behind "launch notebook server" button

### LINKED ISSUE #226: "Launch Notebook Server" URL is broken
This might be by design? It doesn't seem to yield the correct URL, however:

https://testing.datascience.ch/jupyterhub/services/notebooks/undefined/221d52a93f083ba12cc2f2382eef67748f256304/undefined?branch=master

image

### PR DESCRIPTION
**Pull request by ableuler**
Closes #226

### CODE REVIEW

**Comment by rokroskar** [comment]
Does it now also show up when there are already notebooks there?

**Comment by ableuler** [comment]
No, it doesn't. I wasn't sure what exactly the expected behaviour would be (and where this button should show up), so for now I just fixed the thing that is obviously broken.

**Comment by rokroskar** [comment]
Ok, we should add clicking this button to the integration test in renku.

**Comment by ableuler** [comment]
@rokroskar Can you quickly add this button click or approve the PR and create a new issue for more thorough testing of the UI in the integration tests? I'm happy to have a look at splinter at some point, but I don't want a small an simple bugfix PR to be stalled because of this.

**Comment by rokroskar** [comment]
we can make an issue for the integration test -- I was actually just about to try out @leafty's staging set up to deploy this PR...

**Pull request merged**
