### PR TITLE
chore: enforce indent eslint rule

### PR DESCRIPTION
**Pull request by lorenzo-cavazzi**
The `react/jsx-indent` rule was not checking all the indentations.
This fixes that by adding also the eslint `indent` rule.
The second commit fixes the current indent warnings in all the files.

### CODE REVIEW

**Comment by vfried** [comment]
Hey, i'm currently testing this... i'm getting this warning on telepresence:

image

**Comment by vfried** [comment]
> I'm just getting a weird warning that i left in a message above.
> 
> Besides that it looks good.

**Comment by lorenzo-cavazzi** [comment]
oh right, I missed that. An `href` attribute is missing in the `<a>` element since I removed the linting disabler `/* eslint-disable-next-line */`. I have just added it back instead of changing the component -- we could address that with low priority the first time we need to modify it

**Comment by lorenzo-cavazzi** [comment]
ok I rebased and fixed the missing pieces, it's ready

**Pull request merged**
