### PR TITLE
feat: set page title to project or dataset title (#1881)

### LINKED ISSUE #1881: Project page title tag should include the name of the project (to display in browser tab)
Previously, the title for a page in renku was "Renku", now it is "Reproducible Data Science ..." for better SEO, which is fine for the home page, but not informative for other pages.

image

**Projects**
* The title should be set to include the name of the project.
* Description to be the project description.

**Dataset**
* The title should be set to include the title of the dataset.
* Description to be the dataset description.

We probably want to use https://github.com/nfl/react-helmet for this.

### PR DESCRIPTION
**Pull request by ciyer**
Introduces changes to set the title tag as a user navigates through Renku.

- On a project page, the title tag is the title of the project 
- On a dataset page, the title tag is the title of the dataset
- Otherwise, the title tag is "Reproducible Data Science | Open Research | Renku"

closes #1881 

**Project**
image

**Dataset**
image

/deploy renku=tests-ui-2.5.0 #persist

### CODE REVIEW

**Review by andre-code — COMMENTED** [review]
Great addition to improve SEO evaluation and also see Helmet in action, quite easy to modify the metadata. 💫
My only suggestion is to use Title Case, or capitalize only the first letter to make it easier on the eye in the browser tab and search results.

**Comment by ciyer** [comment]
> My only suggestion is to use Title Case, or capitalize only the first letter to make it easier on the eye in the browser tab and search results.

I agree that would look nicer, but the title is something that the user controls, so I want to be careful about changing the formatting without user intervention. Let me solicit some feedback from others to resolve this.

**Comment by ciyer** [comment]
> Great addition to improve SEO evaluation and also see Helmet in action, quite easy to modify the metadata. 💫 My only suggestion is to use Title Case, or capitalize only the first letter to make it easier on the eye in the browser tab and search results.

After some discussions, we have decided to make the title:

`[project/dataset title] •[Project|Dataset] • [project/dataset description, if available]`

**Review by andre-code — APPROVED** [review]
🚀

**Review by andre-code — APPROVED** [review]
🚀

**Pull request merged**
