### PR TITLE
Enable quick navigation through nav bar

### LINKED ISSUE #264: ui: enable nav search bar
The input field in the top nav is now a quick-nav bar making it possible to navigate to a project by typing a portion of its name into the input field. This element will later be improved to include real search capabilities.

### PR DESCRIPTION
**Pull request by ableuler**
Enable project search through a reactive search bar displaying auto-suggestions. This makes it possible to jump to a project quickly.

---
Closes #264.

### CODE REVIEW

**Comment by rokroskar** [comment]
Should this go into 0.2.0?

**Comment by ableuler** [comment]
I'd rather have a working ugly search bar than a pretty (but) useless one, so I vote yes.

**Comment by rokroskar** [comment]
stage?

**Comment by ableuler** [comment]
staged!

**Comment by ableuler** [comment]
👍 looks nice!

**Pull request merged**
