### PR TITLE
New notebook servers page and servers endpoint

### LINKED ISSUE #415: Display notebook servers per project
- [ ] Show list of all running servers under `/notebook-servers/` and connect this to the top `NavBar`.
- [ ] Enable filtering notebook servers per `project_id` in the notebooks service. Requires SwissDataScienceCenter/renku-notebooks#129

**merged** ~contingent on https://github.com/SwissDataScienceCenter/renku-notebooks/issues/125~ 

When this is done, the `/user` endpoint should not be needed anymore -- remember to double check it and ping someone on `renku-notebooks` side to remove it.

### PR DESCRIPTION
**Pull request by lorenzo-cavazzi**
closes #415 

The notebook servers APIs query the new endpoint `notebooks/servers` and the data are used in both the project page `Notebook Servers` and the `Notebooks` page in the top navbar.

@rokroskar once this PR is approved the UI won't use the `notebooks/user` endpoint anymore, neither the UI part from the `renku-notebook` project

Preview: https://lorenzotest.dev.renku.ch

### CODE REVIEW

**Comment by rokroskar** [comment]
Very nice, I don't see any issues with usability for the time being - this is going to be a great starting point for the notebook part of the UI. Only one minor thing:

> You have to start one to connect to Jupiter

Jupiter --> Jupyter :)

> once this PR is approved the UI won't use the notebooks/user endpoint anymore, neither the UI part from the renku-notebook project

Oh good, we can rip those parts out and refactor. It will make that service much leaner.

**Comment by lorenzo-cavazzi** [comment]
updated

**Comment by lorenzo-cavazzi** [comment]
I will address this in #416 since I am going to modify the `/launchNotebook` route

**Comment by vfried** [comment]
> I will address this in #416 since I am going to modify the `/launchNotebook` route
 
Ok, that sounds good.

**Pull request merged**
