### PR TITLE
Bundle together multiple dependency updates

### PR DESCRIPTION
**Pull request by ciyer**
Upgrades to
* bootstrap
* reactstrap
* dompurify

/deploy #persist #cypress renku=000-cypres-tests-new-search

### CODE REVIEW

**Comment by ciyer** [comment]
The navbar elements are too dark in color. 

image

**Comment by ciyer** [comment]
Navbar elements have been corrected, but project header does not have the right padding between elements.

image

**Review by andre-code — CHANGES_REQUESTED** [review]
Overall the application looks good, I only found a change in the font color for the buttons (primary and secondary) in active state.


Screenshot 2023-01-06 at 11 22 12
Screenshot 2023-01-06 at 11 21 24
Screenshot 2023-01-06 at 11 20 25


Also I just noticed that on the resource page the background color changed so the text is now no longer readable, but it's like that in master, maybe you can fix it here.
Screenshot 2023-01-06 at 11 19 57

**Review by lorenzo-cavazzi — APPROVED** [review]
Lgtm! :tada:

**Review by andre-code — APPROVED** [review]
The styles were corrected and it works as expected. 🚀

**Review by lorenzo-cavazzi — APPROVED** [review]

**Pull request merged**
