### PR TITLE
Persistent sessions: small UI updates

### PR DESCRIPTION
**Pull request by leafty**
* Fix the share session link functionality
* Update the paused session status in the dashboard
* Update the pause session modal

Dashboard info:
Screenshot 2023-08-17 at 13 16 51

Pause session modal:
image

/deploy #persist extra-values=notebooks.userSessionPersistentVolumes.enabled=true,notebooks.amalthea.image.repository=renku/amalthea,notebooks.amalthea.image.tag=db70f80ef1983d49a1b167faa57d02d9d8b9554f renku-notebooks=pitch/session-persistence

### CODE REVIEW

**Review by lorenzo-cavazzi — COMMENTED** [review]
This looks good! I have one comment.

The "Create session link" is available only from the project header dropdown button. Should we keep the session dropdown menu consistent or is there a specific reason for that?

image

**Comment by leafty** [comment]
> This looks good! I have one comment.
> 
> The "Create session link" is available only from the project header dropdown button. Should we keep the session dropdown menu consistent or is there a specific reason for that?

Yes, I was thinking that this feature would mostly be accessed from the project's header. I can include the menu option everywhere if we prefer.

**Comment by lorenzo-cavazzi** [comment]
> > This looks good! I have one comment.
> > The "Create session link" is available only from the project header dropdown button. Should we keep the session dropdown menu consistent or is there a specific reason for that?
> 
> Yes, I was thinking that this feature would mostly be accessed from the project's header. I can include the menu option everywhere if we prefer.

If that's a small change, I would keep the menu consistent everywhere

**Comment by leafty** [comment]
> > > This looks good! I have one comment.
> > > The "Create session link" is available only from the project header dropdown button. Should we keep the session dropdown menu consistent or is there a specific reason for that?
> > 
> > 
> > Yes, I was thinking that this feature would mostly be accessed from the project's header. I can include the menu option everywhere if we prefer.
> 
> If that's a small change, I would keep the menu consistent everywhere

Done in 770ff7acd3b8ecff1555564c8b050115d9e3cd10.

**Review by lorenzo-cavazzi — APPROVED** [review]
Lgtm :rocket:

**Pull request merged**
