### PR TITLE
fix(client): use the config.show API for session options

### LINKED ISSUE #2876: Re-invoke the config.show API when changing reference on the Start session page
## Motivation

When renku-core supports passing references to the `GET /config.show` endpoint (see https://github.com/SwissDataScienceCenter/renku-python/issues/3649), we should update the code to start sessions so that selecting a new branch/commit also triggers a new query to update the config for the project.

## Proposal

It should be easy once we can pass the references to the endpoint as a query parameter `branch=<commit-sha>`.
Remember to remove the logic to query the specific file from GitLab.

### PR DESCRIPTION
**Pull request by leafty**
Fixes #2876.

/deploy renku-core=develop

### CODE REVIEW

**Comment by leafty** [comment]
This should not be merged until the endpoint is fixed for anonymous users -> https://github.com/SwissDataScienceCenter/renku-python/issues/3649.

**Review by lorenzo-cavazzi — COMMENTED** [review]
The code looks good :ok_hand: 
I'll make a final review once the backend PR is available and we can fully test the feature

**Comment by leafty** [comment]
Update: the API endpoint seems to work now for signed in users and anonymous users. We can merge when the fix gets released from renku-core.

**Comment by lorenzo-cavazzi** [comment]
Great! 
So we wait for this https://github.com/SwissDataScienceCenter/renku-python/releases/tag/untagged-f93e5d5baa5077e12d89

**Comment by leafty** [comment]
2.9.0 has been tagged, so we can merge this.

**Review by lorenzo-cavazzi — APPROVED** [review]

**Pull request merged**
