### PR TITLE
fix: prevent querying sessions launchers without project id

### PR DESCRIPTION
**Pull request by lorenzo-cavazzi**
When starting a session, the `session_launchers` endpoints is invoked too early when the project id isn't available yet. This prevents it

image

/deploy

### CODE REVIEW

**Review by leafty — APPROVED** [review]

**Review by andre-code — DISMISSED** [review]
lgtm

**Comment by andre-code** [comment]
Thanks to @lorenzo for fixing this!

@leafty, could you clarify what you mean by "not well handled"? I see that the buttons displayed are incorrect. Is there anything else we need to address? If so, we should consider handling those issues in a separate PR.

Screenshot 2024-09-13 at 16 08 28

**Comment by leafty** [comment]
> Thanks to @lorenzo for fixing this!
> 
> @leafty, could you clarify what you mean by "not well handled"? I see that the buttons displayed are incorrect. Is there anything else we need to address? If so, we should consider handling those issues in a separate PR.

We can open a new issue for this, but the component doesn't handle properly when its props are null-ish values

**Comment by lorenzo-cavazzi** [comment]
> We can open a new issue for this, but the component doesn't handle properly when its props are null-ish values

That's a fair point. Since we are fixing the component already, I've added a quick solution for handling invalid namespace/slug values.

**Review by leafty — APPROVED** [review]
LGTM

**Pull request merged**
