### PR TITLE
fix: show a full page 404 when a project is not accessible

### PR DESCRIPTION
**Pull request by leafty**
Details:
* Add a "Error 404 - Project no found" page with contents similar to v1 not found page.
* Refactor the project page v2 routing and components (see [&lt;Outlet&gt;](https://reactrouter.com/en/main/components/outlet) and [useOutletContext()](https://reactrouter.com/en/main/hooks/use-outlet-context))

Examples:
* https://renku-ci-ui-3162.dev.renku.ch/v2/projects/flora.thiebaut/no-project
* https://renku-ci-ui-3162.dev.renku.ch/v2/projects/1234

/deploy

### CODE REVIEW

**Review by ciyer — CHANGES_REQUESTED** [review]
praise: This code improvements here are very nice, and the use of Outlet allows for a better structure to the project page!

I found a situation were the new 404 page *should* be shown, but the old error message is still displayed: https://renku-ci-ui-3162.dev.renku.ch/v2/projects/foo/test/sessions/01HZ79337RV3CCZCQSMW8F0V5F/start

**Comment by leafty** [comment]
> praise: This code improvements here are very nice, and the use of Outlet allows for a better structure to the project page!
> 
> I found a situation were the new 404 page _should_ be shown, but the old error message is still displayed: https://renku-ci-ui-3162.dev.renku.ch/v2/projects/foo/test/sessions/01HZ79337RV3CCZCQSMW8F0V5F/start

Fixed in 7e1015304d1c531ebf2db3d20fc64e6b0daeaf9c.

**Review by ciyer — APPROVED** [review]
Fix looks good!

**Comment by leafty** [comment]
@ciyer can you re-approve? There was a merge conflict and also the "Delete" button redirected to nowhere (fixed).

**Review by ciyer — APPROVED** [review]
LGTM!

**Pull request merged**
