### PR TITLE
feat(design): small fixes for environments inside projects

### PR DESCRIPTION
**Pull request by vfried**
Deleted side tabs, so now when you enter environments inside projects you see this...
image

Form switch fix...
image

Shall we delete the info message?
Shall we make the width of all forms be 12 (max)?

/deploy

### CODE REVIEW

**Comment by ciyer** [comment]
I like these changes! I think getting rid of the tabs is a nice, simplifying improvement. As for your questions, I do not think we should make those changes.

1. I think the info message is helpful and better than seeing an empty sessions list.
2. Let us not worry about the layout of this version of the sessions list because it will change very soon: https://github.com/SwissDataScienceCenter/renku-ui/issues/1219

This PR looks like it branches off another PR with some unrelated changes. I will wait until those changes are merged to review and approve the code.

**Comment by vfried** [comment]
@ciyer thanks for taking a look at this PR.

I just deleted the first commit from this PR, it's "clean" now so that the code can be reviewed.

Regarding the info message, I'm ok with it but then we should add it on every list that is empty to be consistent.

**Comment by ciyer** [comment]
> I just deleted the first commit from this PR, it's "clean" now so that the code can be reviewed.

Code looks good! 🎉 
 
> Regarding the info message, I'm ok with it but then we should add it on every list that is empty to be consistent.

I think it makes sense everywhere where the user can create something (Project list, Dataset list, assuming user has write access to project, etc.)
 
> **I have another concern with this PR** should we make the width of the form be 12? the form inside datasets is but that is a bigger form.

I want to switch to a 2-column layout for the form, as here:

  https://github.com/swissdatasciencecenter/renku-ui/issues/1152

image

If it is an easy fix, we can go ahead and do it now, otherwise, we can merge this PR and make that improvement in another PR.

**Review by ciyer — APPROVED** [review]
👍

**Comment by vfried** [comment]
Let's create a new PR for the two columns form, I want to go ahead and merge these PRs so we can rebase against master

**Pull request merged**
