### PR TITLE
feat(lineage): style data different from code

### PR DESCRIPTION
**Pull request by ciyer**
Style data and code in a way that is more visibly apparent.

### CODE REVIEW

**Comment by vfried** [comment]
Could you add a screenshot of how it looks?

**Comment by ciyer** [comment]
@vfried Please take a look at this change and provide some feedback. I think the result is easier to read and makes the distinction between files that are code and those that are data more clear.

Compare:
  (old)   https://dev.renku.ch/projects/249/files/lineage/src/clean_data.py
  (new) https://sekhar.dev.renku.ch/projects/249/files/lineage/src/clean_data.py

**Comment by ciyer** [comment]
Sure!

### Old

image


### New

image

**Comment by vfried** [comment]
I agree that it's easier to make a difference between nodes... but i'm not a fan of the not styling

Maybe we could add a light grey background

image

or add a thick grey border... 

image

(Personally i prefer the first)

**Comment by ciyer** [comment]
I'm certainly a proponent of "less is more" and removing as much as much as possible, so I prefer the gray border to the gray background, but no background, no border is still my favorite. :) Maybe we can get another pair of eyes here. @lorenzo-cavazzi?

**Comment by lorenzo-cavazzi** [comment]
I am also a minimalist but here I somehow prefer the solution with the borders (no background) to the one without.

**Comment by ciyer** [comment]
How about this thin gray border?

image

**Comment by rokroskar** [comment]
Hmm just looking at this now, styling data as just white with a black border de-emphasizes the data compared to the code. 

Take this view for example:

image

from https://dev.renku.ch/projects/86/files/lineage/img/pc_adelaide.png -- the data cells are barely noticeable.

**Pull request merged**
