### PR TITLE
feat(collaboration): issue form generated from schema and inside collaboration tab

### LINKED ISSUE #697: The Issue/Ku should be created from inside the project/collaboration tab
When a user clicks on create new issue, it should stay inside the collaboration tab.

### LINKED ISSUE #777: Collaboration page duplicate issue creation
## Description

Go to new issue on the collaboration page. If you double-click the "Create" button, the issue gets created twice.

## Reproduce

1. Go to The collaboration page on a project
2. Click on *New Issue*
3. Fill in the form
4. **Double-click** *Create*.

This issue will be created twice.

## Context

- https://dev.renku.ch/
- macOS Catelina
- Chrome  80.0.3987.106

### PR DESCRIPTION
**Pull request by vfried**
Testing available in: https://virginiatest.dev.renku.ch/projects/virginiafriedrich/other-project/collaboration/issues/issue_new

The form was replaced by a schema generated form.

image

Closes #697
Closes #777

### CODE REVIEW

**Comment by vfried** [comment]
Status update: user can write the description of the issue as code or raw markdown.

image

image

**Comment by rokroskar** [comment]
> user can write the description of the issue with the editor or as raw markdown.

amazing. you should tell the people at slack about this! :)

**Comment by vfried** [comment]
> > user can write the description of the issue with the editor or as raw markdown.
> 
> amazing. you should tell the people at slack about this! :)

hahah i saw the slack update

**Comment by vfried** [comment]
Nice!

**Pull request merged**
