### PR TITLE
Header takes up less vertical space

### LINKED ISSUE #1389: Design: make header smaller
# Description

The current header is very large:

By switching to just the frog, we can make the header take up less space, while retaining its functionality. 

# Implementation

- We should aim to have the header size the "standard" bootstrap header size. 
- Try making the icon respond to screen width: for small, just the frog, for large, renku + frog.

### PR DESCRIPTION
**Pull request by ciyer**
# Changes

## Desktop

image

## Mobile

image

/deploy renku=ui-design-2021

Fix #1389

### CODE REVIEW

**Comment by vfried** [comment]
This looks really good, i'm on a smaller screen now and it can really make a difference to have a bit more space in the screen.

Two things to point out:
- padding in the search bar when things are collapse should not be 4... to achieve this you can change the "pe-4" for "pe-0 pe-lg-4" that should do it.
- It would be nice if the amount of space on top and bottom of the frog is the same and to have a bit more space under the search field, etc... we could maybe add some internal padding for this or make the padding on top smaller.

It would be good if Luca reviews this as well, to see that it looks good. But it's not 100% necessary.

**Comment by ciyer** [comment]
> This looks really good, i'm on a smaller screen now and it can really make a difference to have a bit more space in the screen.
> 
> Two things to point out:

I made these changes:

image

image

**Comment by vfried** [comment]
All looks good buuuuut... there is one last issue i found here: when things are collapsed the bar is bigger (height) than when they are not.

**Comment by ciyer** [comment]
> All looks good buuuuut... there is one last issue i found here: when things are collapsed the bar is bigger (height) than when they are not.

Yes, I need to add a little bit of vertical space because the elements were too squashed together, and it didn't look good.

**Review by lorenzo-cavazzi — APPROVED** [review]
Looks nice! :+1: 

I've re-run the acceptance tests cause they were missing the reference to the renku branch `renku=ui-design-2021`

**Pull request merged**
