### PR TITLE
feat(notebooks): always select the latest commit when changing branch

### LINKED ISSUE #588: Automatically load commits after changing the branch in notebook server launch panel
A small issue that I just came across:

After changing the branch in the `Start new JupyterLab server` form, the commits dropdown remains empty until I manually refresh the commits (see screenshot). Changing the branch should automatically trigger loading the available commits. 

image

### PR DESCRIPTION
**Pull request by lorenzo-cavazzi**
Selecting a different branch now automatically select the last available commit -- after the commit list is refreshed.

~Preview available here: https://lorenzotest.dev.renku.ch~

fix #588

### CODE REVIEW

**Comment by ciyer** [comment]
I feel like this new behavior is more intuitive to use. I found a corner case, though. If the project has no commits, then the UI is stuck in `updating branches` forever.

image

https://lorenzotest.dev.renku.ch/projects/cramakri/empty-project/launchNotebook

**Comment by lorenzo-cavazzi** [comment]
The project has neither branches nor commits. How should we behave in this case? Should we just inform the user that an interactive environment requires at least one branch/commit? Or should we provide extra information/instructions?

**Comment by rokroskar** [comment]
I suppose that we should still give them the option of launching a notebook server, but it will be with the instance-configured default image. This would be nice because they don't have to care about any local setup. On the other hand, it might be easier to simply insist that the user makes a commit first.

**Comment by lorenzo-cavazzi** [comment]
At the moment the notebook service requires a `commit_sha` to start a new server. Omitting it results in a 400 error with the following message
> Invalid payload. 'namespace', 'project', and 'commit_sha' are mandatory.

This should be addressed, but it's probably not in the scope of this bugfix PR and is currently affecting every environment. I suggest discussing this in a separate issue -- or in the KG epic /SwissDataScienceCenter/renku#591 if it involves changes in the notebooks service

**Comment by ciyer** [comment]
I think it is adequate to just show a message that a commit is necessary to start an interactive environment, no need to start a server on a project with no commits, since I think this is a rare case. If that is a small change, you can do it here, if it is a larger change then let us make a new issue.

**Comment by lorenzo-cavazzi** [comment]
@ciyer I'll create a new issue for that and I'll work on it right away

**Pull request merged**
